authentication/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import  url

from .forms import LoginForm
from .views import (
    account_login,
    home,
    signup,
    profile_detail,
    update_profile,
    )

urlpatterns = [
    url(r'^accounts/login/$', account_login, name="account_login"),
    url(r'^accounts/signup/$', signup, name="signup"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login'}),
    url(r'^accounts/update-profile/$', update_profile, name="update_profile"),
    url(r'^accounts/profile/$', profile_detail, name="profile_detail"),
    url(r'^$', home, name="home"),

    ]

course/urls.py
from django.conf.urls import url
from .views import (
	chapter_list,
	subchapter_list,
	subsection_list,
	detail,
	)


urlpatterns = [

	url(r'^chapter$', chapter_list, name='chapter_list'),
	url(r'^chapter/(?P<pk>[0-9]+)$', subchapter_list, name='subchapter_list'),
	url(r'^chapter/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', subsection_list, name='subsection_list'),
	url(r'^chapter/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<slug2>[\w-]+)/$', detail, name='detail'),
]

foundation_school/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from rest_framework import routers

from authentication.api.views import AccountViewSet, ProfileViewSet
from authentication.forms import LoginForm
# from course.api

router = routers.DefaultRouter()
router.register(r'accounts', AccountViewSet)
# router.register(r'profile', ProfileViewSet)
# router.register(r'course')


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/fs/', include(router.urls)),
    url(r'^api/fs/course/', include("course.api.urls", namespace="course_api")),
    url(r'^course/', include("course.urls", namespace="course")),
    url(r'', include("authentication.urls", namespace="authentication")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
import os, sys
from PIL import Image

from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


from foundation_school import settings

class AccountManager(BaseUserManager):
    def create_user(self, email, first_name, password=None, **kwargs):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        account = self.model(
            email=self.normalize_email(email),
            first_name = first_name,
            )

        account.set_password(password)
        account.save(using=self._db)
        return account

    def create_superuser(self, email, first_name, password):
        """
        Creates and saves a User with the given email and password.
        """
        account = self.create_user(email, first_name, password=password)
        account.is_admin = True
        account.save(using=self._db)
        return account


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    first_name = models.CharField(max_length=40, blank=False, null=False)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name',]

    def __str__(self):
        return self.email

    def __unicode__(self):
        return self.email

    def get_full_name(self):
        # return ' '.join([self.first_name, self.last_name])
        return self.first_name

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        # "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        # "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        # "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

class Profile(models.Model):
    account = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    last_name = models.CharField(max_length=40, blank=True, null=True, default="not set")

    region = models.CharField(max_length=40, blank=True, null=True, default="not set")
    zone = models.CharField(max_length=40, blank=True, null=True, default="not set")
    church = models.CharField(max_length=40, blank=True, null=True,  default="not set")

    image_medium = models.CharField(max_length=255, blank=True)
    image_thumb = models.CharField(max_length=255, blank=True)

    image = models.ImageField(upload_to=upload_location,
            null=True,
            blank=True,
            )

    def __str__(self):
        return self.account.email

    def __unicode__(self):
        return self.account.email

    def save(self, *args, **kwargs):
        super(Profile, self).save()
        if self.image:
            sizes = {
            'thumbnail': {'height': 100, 'width': 100},
            'medium': {'height': 300, 'width': 300},}

            image_url = str(self.image.url)
            image_path = str(self.image.path)
            fullpath = os.path.split(image_path)[0]

            extension = image_url.rsplit('.', 1)[1]

            image_name = os.path.split(image_url)[1].rsplit('.', 1)[0]
            image_rel_path = os.path.split(image_url)[0]

            im = Image.open(image_path)

            # create medium image
            im.thumbnail((sizes['medium']['width'], sizes['medium']['height']), Image.LANCZOS)
            medname = image_name + "_" + "medium" + ".jpg"
            im.save(os.path.join(fullpath, medname))
            # self.image_medium = (os.path.join(image_rel_path, medname))
            self.image_medium = image_rel_path + "/" + medname

            # create thumbnail image
            im.thumbnail((sizes['thumbnail']['width'], sizes['thumbnail']['height']), Image.LANCZOS)
            thumbname = image_name + "_" + "thumbnail" + ".jpg"
            im.save(os.path.join(fullpath, thumbname))
            # self.image_thumb = (os.path.join(image_rel_path, thumbname))
            self.image_thumb = image_rel_path + "/" + thumbname

            original_image_full_path = os.path.join(settings.BASE_DIR, self.image.path)
            os.remove(original_image_full_path)
            self.image = None

            super(Profile, self).save(*args, **kwargs)


@receiver(post_save, sender=Account)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(account=instance)

@receiver(post_save, sender=Account)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

authentication/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, ReadOnlyPasswordHashField

from .models import Account, Profile

# class LoginForm(AuthenticationForm):
class LoginForm(forms.Form):
    email = forms.CharField(label="Email", max_length=255,
            widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'email'}))
    password = forms.CharField(label="Password", max_length=30,
            widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))


class ContactForm(forms.Form):
    email = forms.EmailField(max_length=200)
    first_name = forms.CharField(max_length=80, required=False)
    last_name = forms.CharField(max_length=80, required=False)
    message = forms.CharField(widget=forms.Textarea)


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password. The name is in line with Django Presets"""
    email = forms.CharField(label='Email',
            widget=forms.EmailInput(attrs={'class': 'form-control',
            'name': 'email'}))
    first_name = forms.CharField(label='first_name',
                widget=forms.TextInput(attrs={'class': 'form-control',
                'name': 'first_name'}))
    password1 = forms.CharField(label='Password',
                widget=forms.PasswordInput(attrs={'class': 'form-control',
                'name': 'password1'}))
    password2 = forms.CharField(label='Password confirmation',
                 widget=forms.PasswordInput(attrs={'class': 'form-control',
                 'name': 'password2'}))

    class Meta:
        model = Account
        fields = ('email', 'first_name')

    def clean_password2(self):
    # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        account = super(UserCreationForm, self).save(commit=False)
        account.set_password(self.cleaned_data["password1"])
        if commit:
            account.save()
        return account


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field. The name is in line with Django Presets
    """
    password = ReadOnlyPasswordHashField()
    class Meta:
        model = Account
        fields = ('email', 'password', 'first_name', 'is_active', 'is_admin')
        # fields = ('first_name', 'password',)

    def clean_password(self):
    # Regardless of what the user provides, return the initial value.
    # This is done here, rather than on the field, because the
    # field does not have access to the initial value
        return self.initial["password"]

class AccountForm(forms.ModelForm):
    email = forms.CharField(label='Email',
            widget=forms.EmailInput(attrs={'class': 'form-control',
            'name': 'email', 'readonly':True}))
    first_name = forms.CharField(label='First name',
                widget=forms.TextInput(attrs={'class': 'form-control',
                'name': 'first_name'}))
    class Meta:
        model = Account
        fields = ('email','first_name',)


class ProfileForm(forms.ModelForm):
    last_name = forms.CharField(label='Last name', required=False,
                widget=forms.TextInput(attrs={'class': 'form-control',
                'name': 'last_name'}))
    region = forms.CharField(label='region', required=False,
                widget=forms.TextInput(attrs={'class': 'form-control',
                'name': 'region'}))
    zone = forms.CharField(label='zone', required=False,
                widget=forms.TextInput(attrs={'class': 'form-control',
                'name': 'zone'}))
    church = forms.CharField(label='church', required=False,
                widget=forms.TextInput(attrs={'class': 'form-control',
                'name': 'church'}))
    class Meta:
        model = Profile
        fields = ('image', 'last_name', 'region', 'zone', 'church',)

authentication/api/views.py
from rest_framework import permissions, status, viewsets
from rest_framework.response import Response

from authentication.models import Account, Profile
from .permissions import IsAccountOwner
from .serializers import AccountSerializer, ProfileSerializer


class AccountViewSet(viewsets.ModelViewSet):
    lookup_field = 'email'
    lookup_value_regex = "([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)"
    queryset = Account.objects.all()
    serializer_class = AccountSerializer

    def get_permissions(self):
        if self.request.method in permissions.SAFE_METHODS:
            return (permissions.AllowAny(),)

        if self.request.method == 'POST':
            return (permissions.AllowAny(),)

        return (permissions.IsAuthenticated(), IsAccountOwner(),)

    def create(self, request):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            Account.objects.create_user(**serializer.validated_data)

            return Response(serializer.validated_data, status=status.HTTP_201_CREATED)

        return Response({
            'status': 'Bad request',
            'message': 'Account could not be created with received data.'
        }, status=status.HTTP_400_BAD_REQUEST)


class ProfileViewSet(viewsets.ModelViewSet):
    # lookup_field = 'email'
    # lookup_value_regex = "([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)"
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer

    def get_permissions(self):
        if self.request.method in permissions.SAFE_METHODS:
            return (permissions.AllowAny(),)

        if self.request.method == 'POST':
            return (permissions.AllowAny(),)

        return (permissions.IsAuthenticated(), IsAccountOwner(),)

    def create(self, request):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            Profile.objects.create_user(**serializer.validated_data)

            return Response(serializer.validated_data, status=status.HTTP_201_CREATED)

        return Response({
            'status': 'Bad request',
            'message': 'Profile could not be created with received data.'
        }, status=status.HTTP_400_BAD_REQUEST)

authentication/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.utils.translation import ugettext_lazy as _


from .admin import UserCreationForm
from .forms import LoginForm, ProfileForm, AccountForm
from .models import Account, Profile


@login_required(login_url="accounts/login/")
def home(request):
    user = request.user
    first_name = user.first_name
    context = {
    "first_name" : first_name,
    }
    return render(request,"home.html", context)


def account_login(request):
    if request.user.is_authenticated():
        return redirect("/")
    else:
        form = LoginForm(request.POST or None)
        next_url = request.GET.get('next')
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user is not None:
        	    login(request, user)
        	    if next_url is not None:
        		    return HttpResponseRedirect(next_url)
            return HttpResponseRedirect("/")
        title = "Login"
        submit_btn = title
        submit_btn_class = "btn-success btn-block"
        context = {
        "form": form,
        "title": title,
        "submit_btn": submit_btn,
        "submit_btn_class": submit_btn_class,
        }
        return render(request, "login.html", context)


def signup(request):
    if request.user.is_authenticated():
        return redirect("/")
    else:
        form = UserCreationForm(request.POST or None)
        if form.is_valid():
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            password = form.cleaned_data['password2']
            #MyUser.objects.create_user(first_name=first_name, email=email, password=password)
            new_user = Account()
            new_user.email = email
            new_user.first_name = first_name
            #new_user.password = password #WRONG
            new_user.set_password(password) #RIGHT
            new_user.save()
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
            return HttpResponseRedirect("/")

        title = "Register"
        submit_btn = "Create free account"

        context = {
        "form": form,
        "title": title,
        "submit_btn": submit_btn
        }
        return render(request, "signup.html", context)


# @transaction.atomic
@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = AccountForm(request.POST or None, instance=request.user)
        profile_form = ProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('authentication:profile_detail')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = AccountForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile_update.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def profile_detail(request):
    user = request.user
    profile = user.profile
    context = {
    "user": user,
    "profile": profile,
    }
    return render(request, "profile.html", context)

authentication/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
{% if form.errors %}
<div class="btn-danger">
  {% for error in form.errors %}
  <h2>{{error}}</h2>
  {% endfor %}
</div>
{% endif %}

  {% if next %}
    {% if user.is_authenticated %}

      <p>Your account doesn't have access to this page. To proceed,
          please login with an account that has access.</p>
    {% else %}

      <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-6">
      <div class="login-panel panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Please Sign In</h3>
        </div>
        <div class="panel-body">
          <form method="post" action="{% url 'authentication:account_login' %}">
            {% csrf_token %}
            {{form.as_p}}

            <p>
              <input class="btn btn-success btn-sm" type="submit" value="Login"/>
              Don't have an acccount?
              <span>
                <a href="{% url 'authentication:signup' %}">Sign Up</a>
              </span>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block javascript %}


<script>
  {% if not user.is_authenticated %}
    $("ul.nav.navbar-nav.navbar-right").css("display","none");
  {% endif %}
</script>

{% endblock %}

authentication/templates/profile.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'authentication/css/profile.css' %}" media="screen" title="no title" charset="utf-8">
{% endblock css %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div class="">
        <div class="">
          <img src="{{ user.profile.image_medium }}" alt="profile picture" class="" />
        </div>
        <h3>Email: {{ user.email }}</h3>
        <h3>First name: {{ user.first_name }}</h3>
        <h3>Last name: {{ user.profile.last_name }}</h3>
        <h3>Region: {{ user.profile.region }}</h3>
        <h3>Zone: {{ user.profile.zone }}</h3>
        <h3>Church: {{ user.profile.church }}</h3>
        <!-- <h3>{{ user.first_name }}</h3> -->
      </div>
      <div class="">
        <a href="{% url 'authentication:update_profile'%}">Update Profile</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

authentication/templates/profile_update.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-4 well">
      <form method="POST" class="form-horizontal" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.media }}
        {{ profile_form.as_p }}
        <button type="submit" class="btn btn-block btn-success">Save changes</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

authentication/templates/signup.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}
{% if form.errors %}
<div class="btn-danger">
  {% for error in form.errors %}
  <h2>{{error}}</h2>
  {% endfor %}
</div>
{% endif %}

  {% if next %}
    {% if user.is_authenticated %}

      <p>Your account doesn't have access to this page. To proceed,
          please login with an account that has access.</p>
    {% else %}

      <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Create Account</h3>
                </div>
                <div class="panel-body">
                  <form method="post" action="{% url 'authentication:signup' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>
                    <input class="btn btn-primary btn-sm" type="submit" value="Submit" />
                      Have an acccount already?
                    <span>
                      <a href="{% url 'authentication:account_login' %}">Login</a>
                    </span>
                    </p>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}

<script>
  {% if not user.is_authenticated %}
    $("ul.nav.navbar-nav.navbar-right").css("display","none");
  {% endif %}
</script>

{% endblock %}