course/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    ChapterDetailAPIView,
    ChapterListAPIView,
    )

urlpatterns = [
    url(r'^$', ChapterListAPIView.as_view(), name='list'),
    url(r'^(?P<pk>[\w-]+)/$', ChapterDetailAPIView.as_view(), name='detail'),
]

course/urls.py
from django.conf.urls import url
from .views import (
	chapter_list,
	subchapter_list,
	subsection_list,
	detail,
	)


urlpatterns = [

	url(r'^chapter$', chapter_list, name='chapter_list'),
	url(r'^chapter/(?P<pk>[0-9]+)$', subchapter_list, name='subchapter_list'),
	url(r'^chapter/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', subsection_list, name='subsection_list'),
	url(r'^chapter/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<slug2>[\w-]+)/$', detail, name='detail'),
]

foundation_school/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from rest_framework import routers

from authentication.api.views import AccountViewSet, ProfileViewSet
from authentication.forms import LoginForm
# from course.api

router = routers.DefaultRouter()
router.register(r'accounts', AccountViewSet)
# router.register(r'profile', ProfileViewSet)
# router.register(r'course')


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/fs/', include(router.urls)),
    url(r'^api/fs/course/', include("course.api.urls", namespace="course_api")),
    url(r'^course/', include("course.urls", namespace="course")),
    url(r'', include("authentication.urls", namespace="authentication")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Chapter(models.Model):
	title = models.CharField(max_length=200, unique=True)
	slug = models.SlugField(unique=True)
	date_completed = models.DateTimeField(blank=True, null=True)

	completed = models.BooleanField(default=False)

	def __str__(self):
		return self.title


class SubChapter(models.Model):
	chapter = models.ForeignKey(Chapter)
	title = models.CharField(max_length=200, unique=True)
	slug = models.SlugField(unique=True)

	completed = models.BooleanField(default=False)

	def __str__(self):
		return self.title


class SubSection(models.Model):
	sub_chapter = models.ForeignKey(SubChapter)
	title = models.CharField(max_length=200, unique=True)
	slug = models.SlugField(unique=True)
	text = models.TextField(null=True, blank=False)

	completed = models.BooleanField(default=False)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("course:detail", kwargs={"slug":self.sub_chapter.slug, "slug2":self.slug, "pk":self.sub_chapter.chapter.pk,
		})

course/api/views.py
from django.db.models import Q


from rest_framework.filters import (
        SearchFilter,
        OrderingFilter,
    )
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    UpdateAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView
    )


from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,

    )

from course.models import Chapter, SubChapter


from .serializers import (
    ChapterSeriaizer,
    SubChapterSeriaizer,
    )


class ChapterDetailAPIView(RetrieveAPIView):
    queryset = Chapter.objects.all()
    serializer_class = SubChapter
    # lookup_field = 'id'
    permission_classes = [AllowAny]


class ChapterListAPIView(ListAPIView):
    serializer_class = ChapterSeriaizer
    filter_backends= [SearchFilter, OrderingFilter]
    permission_classes = [AllowAny]
    search_fields = ['title', 'content', 'user__first_name']
    # pagination_class = ChapterPageNumberPagination #PageNumberPagination

    def get_queryset(self, *args, **kwargs):
        #queryset_list = super(ChapterListAPIView, self).get_queryset(*args, **kwargs)
        queryset_list = Chapter.objects.all() #filter(user=self.request.user)
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                    Q(title__icontains=query)|
                    Q(content__icontains=query)|
                    Q(user__first_name__icontains=query) |
                    Q(user__last_name__icontains=query)
                    ).distinct()
        return queryset_list

course/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Chapter, SubChapter, SubSection
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect

def chapter_list(request):
	chapters = Chapter.objects.all()
	return render(request, 'cefs/chapter_list.html', {'chapters':chapters})

def subchapter_list(request, pk):
	chapter = get_object_or_404(Chapter, pk=pk)
	subchapters = chapter.subchapter_set.all()
	return render(request, 'cefs/subchapter_list.html', {'subchapters':subchapters, 'chapter':chapter})

def subsection_list(request, pk, slug):
	sub_chapter = get_object_or_404(SubChapter, slug=slug)
	sub_sections = sub_chapter.subsection_set.all()
	chapter = get_object_or_404(Chapter, pk=pk)
	return render(request, 'cefs/sub_section_list.html', {'sub_sections':sub_sections, 'chapter':chapter, 'sub_chapter':sub_chapter})

# edit this to determine how subsections are queried and published
def detail(request, pk, slug, slug2):
	chapter = get_object_or_404(Chapter, pk=pk)
	subsection = get_object_or_404(SubChapter, slug=slug)
	course = get_object_or_404(SubSection, slug=slug2)
	course_id = course.pk
	next_course_pk = course_id + 1
	next_course = get_object_or_404(SubSection, pk=next_course_pk)
	context = {
	'course':course,
	'chapter':chapter,
	'subsection':subsection,
	'next_course': next_course,
	}
	return render(request, 'cefs/detail.html', context)

course/templates/cefs/base.html
{% load staticfiles %}

<html>
<head>
<title> CE Foundations</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<script src="{% static 'js/respond.js' %}"></script>
      {% block css %}
      {% endblock %}
</head>

<body>

{% block content %}

{% endblock %}
<div class="copyrights">&copy; {% now "Y" %} Christ Embassy Inc</div>

<!-- jquery javascript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

course/templates/cefs/base1.html
{% load staticfiles %}
<html>
<head>
<title> CE Foundations</title>
<link rel="stylesheet" href="{% static 'css/cefs.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="{% static 'js/respond.js' %}"></script>

</head>

<body>

{% block content %}
{% endblock %}


<!-- jquery javascript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

course/templates/cefs/chapter_list.html
{% extends 'cefs/base.html' %}
{% load staticfiles %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/chapter_list.css' type="text/css" %}">
{% endblock %}

{% block content %}

	<div class="theNavBar">
		<div class="titleHeader">
			<p class='schoolTitle'>Christ Embassy Foundation School</p>
		</div>
	</div>
	<div class="classContainer">
	{% for chapter in chapters %}
	<a href="{% url 'course:subchapter_list' pk=chapter.pk %}">
		<div class="classes">
			<h2>
				 Class {{ chapter.pk }}: {{ chapter.title }}
			</h2>
		</div>
	</a>

	{% endfor %}
	</div>

{% endblock %}

course/templates/cefs/detail.html
{% extends 'cefs/base.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block content %}

<nav class="theNavBar">
	<div class="titleHeaders">
		<p class="chapterTitle">{{ chapter.title}}</p>
		<p class="subsectionTitle">{{ subsection.title}}</p>
		<p class='courseTitle'>{{ course.title}}</p>
	</div>

	<a href="{% url 'course:subsection_list' pk=subsection.chapter.pk slug=subsection.slug %}">
		<img class ="backArrow" src="{% static 'imgs/backArrow.PNG' %}">
	</a>
</nav>

<div class="content">
	<div class="contentContainer">
	  <p>{{ course.text | safe}}</p>
  	</div>

  	<div class="logos">
  		<div class="qa">
  			<a href="#"><img src="{% static 'imgs/qa.PNG' %}"></a>
  		</div>

		<div class="greenButton">
			<a href= "{{next_course.get_absolute_url}}">
				<img src="{% static 'imgs/greenButton.PNG' %}">
			</a>
  		</div>
	</div>
</div>	
{% endblock %}

course/templates/cefs/sub_section_list.html
{% extends 'cefs/base.html' %}
{% load staticfiles %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/sub_section_list.css' %}">
{% endblock %}

{% block content %}
	<nav class="theNavBar">
		<a href="{% url 'course:subchapter_list' pk=chapter.pk %}">
			<img class ="backArrow" src="{% static 'imgs/backArrow.PNG' %}">
		</a>

		<div class="titleHeaders">
			<p class="chapterTitle">{{ chapter.title}}</p>
			<p class='subchapterTitle'>{{ sub_chapter.title}}
			</p>
		</div>
	</nav>
<div class="content">
	{% for subsection in sub_sections %}
	<a href="{% url 'course:detail'  pk=subsection.sub_chapter.chapter.pk slug=subsection.sub_chapter.slug slug2=subsection.slug %}">

	<div class="subsectionContent">
		  	<div class="section">
		  		{{ subsection.title }}
		  	</div>
	</div>
	</a>
	
{% endfor %}
</div>

{% endblock %}

course/templates/cefs/subchapter_list.html
{% extends 'cefs/base.html' %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/subchapter_list.css' %}">
{% endblock %}

{% block content %}

	<div class="theNavBar">
		<a href="{% url 'course:chapter_list' %}">
			<img class ="backArrow" src="{% static 'imgs/backArrow.PNG' %}">
		</a>

		<div class="titleHeader">
			<p class='chapterTitle'>{{chapter.title}}</p>
		</div>
	</div>


	<div class="content">
	{% for subchapter in subchapters %}	
	<a href="{% url 'course:subsection_list' pk=subchapter.chapter.pk slug=subchapter.slug %}">
		<div class="subsectionContent">
			<div class="section">
				{{ subchapter.title }}
			</div>
		</div>
	</a>

	{% endfor %}
	</div>

{% endblock %}