authentication/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import  url

from .forms import LoginForm
from .views import (
    account_login,
    home,
    signup,
    profile_detail,
    update_profile,
    )

urlpatterns = [
    url(r'^accounts/login/$', account_login, name="account_login"),
    url(r'^accounts/signup/$', signup, name="signup"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login'}),
    url(r'^accounts/update-profile/$', update_profile, name="update_profile"),
    url(r'^accounts/profile/$', profile_detail, name="profile_detail"),
    url(r'^$', home, name="home"),

    ]

course/urls.py
from django.conf.urls import url
from .views import (
	chapter_list,
	subchapter_list,
	subsection_list,
	detail,
	)


urlpatterns = [

	url(r'^chapter$', chapter_list, name='chapter_list'),
	url(r'^chapter/(?P<pk>[0-9]+)$', subchapter_list, name='subchapter_list'),
	url(r'^chapter/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', subsection_list, name='subsection_list'),
	url(r'^chapter/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/(?P<slug2>[\w-]+)/$', detail, name='detail'),
]

foundation_school/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from rest_framework import routers

from authentication.api.views import AccountViewSet, ProfileViewSet
from authentication.forms import LoginForm
# from course.api

router = routers.DefaultRouter()
router.register(r'accounts', AccountViewSet)
# router.register(r'profile', ProfileViewSet)
# router.register(r'course')


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/fs/', include(router.urls)),
    url(r'^api/fs/course/', include("course.api.urls", namespace="course_api")),
    url(r'^course/', include("course.urls", namespace="course")),
    url(r'', include("authentication.urls", namespace="authentication")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- Core CSS - Include with every page -->
      <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

      {% block css %}
      {% endblock css %}
      <title>{% block title %}Foundation School{% endblock%}</title>
    </head>
    <body>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#account_dropdown">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand" href="/">Foundation School</a>
          </div>
            <div class="collapse navbar-collapse" id="account_dropdown">
              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li>
                      <a href="/">home</a>
                    </li>
                    <li>
                      <a href="{% url 'authentication:profile_detail'%}">Profile</a>
                    </li>
                    <li>
                      <a href="{% url 'course:chapter_list' %}">Course</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                      <a href="#">Separated link</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                      <a href="/logout">Logout</a>
                    </li>
                  </ul>
                </li>
              </ul>
          </div>
        </div>
      </nav>

      {% block content %}
      {% endblock %}


    <!-- Core Scripts - Include with every page -->
      <script src = "{% static 'js/jquery-1.11.3.js' %}"></script>
      <script src = "{% static 'js/bootstrap.min.js' %}"></script>
      {% block javascript %}
      {% endblock %}

    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="jumbotron">
            <h1>Hello {{first_name}}</h1>
            <p>This is your Dashboard</p>
            <p>
              Go to <a href="{% url 'course:chapter_list' %}">course</a>
            </p>
        </div>
    </div>
</div>

{% endblock %}